### ISSUE TITLE
Add Oracle JDK support to Docker multi-container setup.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-CLAW/CLAW#219]
Currently only Open JDK is supported, I suspect that the problems related to Oracle JDK were also the same problems Kernal problems as is noted in the [read me's](https://github.com/islandora-claw/claw-docker#kernal-issues).

**Comment by nigelgbanks** [comment]
Added support and tested it, everything seems to be working correctly. 

Here are the pulls to fix the issue:
https://github.com/Islandora-CLAW/claw-docker/pull/9
https://github.com/Islandora-CLAW/claw-docker-islandora-karaf-components/pull/3
https://github.com/Islandora-CLAW/claw-docker-tomcat/pull/3
https://github.com/Islandora-CLAW/claw-docker-solr/pull/3
https://github.com/Islandora-CLAW/claw-docker-maven/pull/3
https://github.com/Islandora-CLAW/claw-docker-karaf/pull/3
https://github.com/Islandora-CLAW/claw-docker-blazegraph/pull/3
https://github.com/Islandora-CLAW/claw-docker-fedora/pull/3

To test you'll need to pull down all the relevant changes into your local copy of https://github.com/Islandora-CLAW/claw-docker images directories (from my repo's), and build the multi-container images using ./commands/build. Once that's done this docker-compose.yml file can be used for testing.

```yaml
version: "2"
volumes:
  blazegraph:
  drupal:
  fedora:
  karaf:
  mariadb:
  solr:
services:

  # Un-comment to enable etcd as the back end for storing environment variables.

  # etcd:
  #   image: quay.io/coreos/etcd:v2.3.0
  #   command: >
  #     -listen-client-urls http://0.0.0.0:2379
  #     -advertise-client-urls http://etcd:2379
  #   ports:
  #     - "2379:2379" 

  # Registers each container as it's started in etcd, so it can be used as a
  # prefix for storing configuration settings, also for Discovery in
  # multi-network system.

  # registrator:
  #   image: gliderlabs/registrator
  #   command: "etcd://etcd:2379"
  #   volumes:
  #     - "/var/run/docker.sock:/tmp/docker.sock"
  #   links:
  #     - etcd

  mariadb:
    image: islandora/claw-mariadb
    env_file: env_files/mariadb.env
    volumes:
      - "mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"

  fedora:
    image: islandora/claw-fedora:oracle-jdk
    env_file: env_files/fedora.env
    volumes:
      - "fedora:/mvn/fedora-data"
    ports:
      - "8080:8080"

  blazegraph:
    image: islandora/claw-blazegraph:oracle-jdk
    env_file: env_files/blazegraph.env
    volumes:
      - "blazegraph:/opt/blazegraph"
    ports:
      - "8081:8080"

  solr:
    image: islandora/claw-solr:oracle-jdk
    env_file: env_files/solr.env
    volumes:
      - "solr:/opt/solr/collection1/data"
    ports:
      - "8082:8080"

  karaf:
    image: islandora/claw-islandora-karaf-components:oracle-jdk
    env_file:
      - env_files/karaf.env
      - env_files/drupal.env
    volumes:
      - "karaf:/opt/karaf/data"
    ports:
      - "8181:8181"

  drupal:
    image: islandora/claw-islandora
    env_file:
      - env_files/drupal.env
      - env_files/mariadb.env
    volumes:
      -  "drupal:/var/www/localhost/htdocs/sites/default/files"
    ports:
      - "80:80"
    links:
      - "mariadb:mysql" 
```
