### ISSUE TITLE
Implement a POST request for FedoraResource entities

### ISSUE THREAD

**Issue by dannylamb** [Islandora-CLAW/CLAW#525]
Implement a POST request to create fedora resources, exposing an endpoint at http://localhost:8000/fedora_resource/ that has the following behaviour:

* Respects the drupal/symfony _format query parameter
* Expects the bundle as a header, X-Islandora-Bundle, so the resource can be unambiguously created (only required when _format=jsonld)
* Expects proper Content-Type header (despite the _format parameter)
* Respects an optional checksum header to verify upload.

Possible responses:
* Returns 201 with the newly created resource as the response
* Returns 409 if checksum mismatch

**Comment by dannylamb** [comment]
@whikloj @ajs6f What do you think about this? 

> Expects the bundle as a header, X-Islandora-Bundle, so the resource can be unambiguously created (only required when _format=jsonld)

For the MVP, this would limit the use of the bundle resolver significantly.  Basically just for data coming from fcrepo that's not in drupal yet.

**Comment by whikloj** [comment]
👍  I like this. It also needs to respect JWTs. 

I'm not sure what you would use the `_format` for as I can only think of sending your data as JSON-LD?

**Comment by Natkeeran** [comment]
@dannylamb, can you please confirm the following steps to implement this endpoint:

* Add a path to the route
```
islandora.post:
  path: 'fedora_resource'
  defaults: { _controller: '\Drupal\islandora\Controller\FedoraResourcePOSTController::processPost' }
  methods:  [POST]
  requirements:
    _access: 'TRUE'
```
* Implement the FedoraResourcePOSTController.
* Check checksum
* If mismatch, return 404
* If good, create the bundle as per the request
* Return 201 with json-ld of the created bundle!
