### ISSUE TITLE
Ansible for CLAW Vagrant

### ISSUE THREAD

**Issue by jonathangreen** [Islandora-CLAW/CLAW#657]
What do we think of provisioning CLAW vagrant with Ansible instead of shell scripts? 

I've been working on a playbook to do that [here](https://github.com/jonathangreen/claw-playbook). Its by no means ready yet, but it is coming along. I've been building it taking some cues (and code) from both [CLAW vagrant](https://github.com/Islandora-CLAW/claw_vagrant) and the [CLAW Ansible](https://github.com/islandora-deprecated/claw-ansible).

I have a couple things I'm trying to do with this:  
- Use as many roles from Ansible galaxy as possible
- Make it as easy to extend the roles as I can
- Try to follow [best practices](http://docs.ansible.com/ansible/playbooks_best_practices.html)
- Make is possible to deploy stack in multiple pieces as well as all together

Roadmap:
1. Get feature parity with CLAW Vagrant
2. Break each role out into its own git repo, so they can be listed on galaxy
3. Test install on multiple boxes
4. Test with other operating systems (?) 
5. ...
6. profit!

I would like in the end to have the vagrant inventory be an example how one could use the collection of roles to deploy a production CLAW stack on metal. 

So I guess my main question is if there is any interest from everyone in having CLAW vagrant deploy with Ansible instead of shell scripts? 

If you want to get a feel for how that would work, you can check out my repo and as long as you have ansible installed on the host computer, you should be able to `vagrant up` and see it in action. Should be able to see islandora at http://localhost:8000 once its done.

**Comment by whikloj** [comment]
I am interested, but I have no idea what any of this does. My feeling is that we need more people to understand the provisioning or else we are (as we were with the Docker stuff) stuck relying on one or two people to do everything. For instance why are there two entries in [this file](https://github.com/jonathangreen/claw-playbook/blob/master/roles/internal/blazegraph/tasks/config.yml) that do the same thing? 

Also is the directory structure important? 

I'm definitely not against this, I'm just saying that if we go to Ansible now. I will not be able to assist in doing...anything. So we might rely heavily on you.

**Comment by jonathangreen** [comment]
I totally agree Jared. I guess maybe a good way to frame this question would be: do we as the CLAW project want to take on Ansible as a technology. We already have a lot of different technologies (acronym soup) and maybe we don't need to take on another. On the other hand I do think that Ansible scripts are superior to shell scripts for provisioning in almost every way, except for the overhead of understanding Ansible. I will however admit I'm biased as I use Ansible a lot already. 

I know this is kind of orthogonal to your point, but to answer your specific questions about Ansible:

In the [file you mentioned](https://github.com/jonathangreen/claw-playbook/blob/master/roles/internal/blazegraph/tasks/config.yml), those two entires don't do the same thing. 

```yaml
- name: Copy templated blazegraph config files
  template:
    src: "{{ item }}"
    dest: "{{ blazegraph_home_dir }}/conf/{{ item }}"
    owner: "{{ blazegraph_user }}"
    group: "{{ blazegraph_user }}"
  with_items:
    - RWStore.properties
  notify: restart tomcat8
```
The template line in this one is important in that it is calling the [template module](http://docs.ansible.com/ansible/template_module.html) to template the [RWStore.properties](https://github.com/jonathangreen/claw-playbook/blob/master/roles/internal/blazegraph/templates/RWStore.properties) file.

```yaml
- name: Copy blazegraph config files
  copy:
    src: "{{ item }}"
    dest: "{{ blazegraph_home_dir }}/conf/{{ item }}"
    owner: "{{ blazegraph_user }}"
    group: "{{ blazegraph_user }}"
  with_items:
    - blazegraph.properties
    - inference.nt
  notify: restart tomcat8
```
This entry uses the [copy module](http://docs.ansible.com/ansible/copy_module.html) to just directly copy the [blazegraph.properties](https://github.com/jonathangreen/claw-playbook/blob/master/roles/internal/blazegraph/files/blazegraph.properties) and [inference.nt](https://github.com/jonathangreen/claw-playbook/blob/master/roles/internal/blazegraph/files/inference.nt) files, without running them through the templating engine.

The playbook directory structure makes things easier in that if files are in certain folders they are included automatically. The [playbook roles](http://docs.ansible.com/ansible/playbooks_roles.html#roles) section of the [Ansible Docs](http://docs.ansible.com/ansible/index.html) does a good job explaining the folder structure. More generally if you are interested in learning Ansible reading the whole [Playbooks](http://docs.ansible.com/ansible/playbooks.html) section of the docs is a really good introduction, but there is a lot of content there.
